server:
  port: 8775
eureka:
  client:
    service-url:
      defaultZone:  http://user:123456@localhost:8771/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: springcloudstuclient2
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gannan17?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
feign:
  hystrix:
    enabled: true
hystrix:
  dashboard:
    proxy-stream-allow-list: localhost
